name: 'Bug report'
description: Create a report to help us improve
title: '[BUG]: '
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      value: 'about the bug'
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      value: 'write steps'
      placeholder: Steps to reproduce.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      value: 'write expected behaviour'
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
      value: 'explain'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      value: 'add screenshots'
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      value: 'add comments'
      placeholder: e.g. some background/context of how you ran into this bug.
