name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: '@mindfiredigital/pagebuilder Build'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: 'Install dependencies with pnpm'
        run: pnpm install 

      - name: 'Build application'
        run: pnpm turbo run build

      - name: 'Restore changes in pnpm lock'
        run: git restore pnpm-lock.yaml

      - name: 'Set Git user name and email'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub Release and Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Publish Package and Create GitHub Release
        run: |
          cd packages/cli  # Navigate to the core package directory
          pnpm install --frozen-lockfile  # Ensure dependencies are installed
          pnpm build  # Build the core package
          npx semantic-release  # Run semantic release to publish and create GitHub release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB }} 
