name: Core Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: '@craftfosslabs/dragifyjs Build'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install pnpm
        run: npm install -g pnpm

      - name: 'Install dependencies with pnpm'
        run: pnpm install

      - name: 'Build Core package'
        run: |
          cd packages/cli
          pnpm build  # Run build script specific to the CLI package
          cd ../..

      - name: 'Restore changes in pnpm lock'
        run: git restore pnpm-lock.yaml

      - name: 'Set Git user name and email'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub release document and publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Semantic Release and npm release
        run: |
          cd packages/cli
          pnpm install --frozen-lockfile
          pnpm build  # Ensure the CLI package is built before release
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB }}
