name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: '@mindfiredigital/pagebuilder Build'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.15.2

      - name: 'Install dependencies with pnpm'
        run: pnpm install 

      - name: 'Build application'
        run: pnpm turbo run build

      - name: 'Restore changes in pnpm lock'
        run: git restore pnpm-lock.yaml

      - name: 'Set Git user name and email'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  release:
    name: Create GitHub Release and Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure clean working directory
        run: git restore --staged . && git restore .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.15.2

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build the Core Package
        run: |
          cd packages/cli
          pnpm install --frozen-lockfile
          pnpm build

      - name: Publish Package to npm
        run: |
          cd packages/cli
          pnpm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        run: |
          echo "Creating GitHub Release"
          git tag v$(jq -r '.version' < packages/cli/package.json)
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB }}
